/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserInfo {
  sub: string;
  email?: string | null;
  name?: string | null;
  preferred_username?: string | null;
}
