/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthInfo } from './authInfo';
import { UserInfo } from './userInfo';


export interface UserInfoDTO { 
    authInfo: AuthInfo;
    userInfo: UserInfo;
}

